# Tarea 10

Estudiante: Anthony Alangasí

Grupo: GR1CC

Fecha: 28/01/2026

### CONJUNTO DE EJERCICIOS

1. Realice las siguientes multiplicaciones matriz-matriz:
$$
   a) \begin{pmatrix} 2 & -3 \\ 3 & -1 \end{pmatrix} \begin{pmatrix} 1 & 5 \\ 2 & 0 \end{pmatrix}
$$

In [43]:
import numpy as np

A_1 = [[2, -3], [3, -1]]
B_1 = [[1, 5], [2, 0]]

Matriz_A1xB1 = np.matmul(A_1, B_1)
print("Matriz A1 x B1:\n", Matriz_A1xB1)

Matriz A1 x B1:
 [[-4 10]
 [ 1 15]]


$$
   b) \begin{pmatrix} 2 & -3 \\ 3 & -1 \end{pmatrix} \begin{pmatrix} 1 & 5 & -4 \\ -3 & 2 & 0 \end{pmatrix}
$$

In [44]:
A_2 = [[2, -3], [3, -1]]
B_2 = [[1, 5, -4], [-3, 2, 0]]

Matriz_A2xB2 = np.matmul(A_2, B_2)
print("Matriz A2 x B2:\n", Matriz_A2xB2)

Matriz A2 x B2:
 [[ 11   4  -8]
 [  6  13 -12]]


$$
   c) \begin{pmatrix} 2 & -3 & 1 \\ 4 & 3 & 0 \\ 5 & 2 & -4 \end{pmatrix}  \begin{pmatrix} 0 & 1 & -2 \\ 1 & 0 & -1 \\ 2 & 3 & -2 \end{pmatrix}
$$

In [45]:
A_3 = [[2, -3, 1], [4, 3, 0], [5, 2, -4]]
B_3 = [[0, 1, -2], [1, 0, -1], [2, 3, -2]]

Matriz_A3xB3 = np.matmul(A_3, B_3)
print("Matriz A3 x B3:\n", Matriz_A3xB3)

Matriz A3 x B3:
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


$$
   d) \begin{pmatrix} 2 & 1 & 2 \\ -2 & 3 & 0 \\ 2 & -1 & 3 \end{pmatrix}  \begin{pmatrix} 1 & -2 \\ -4 & 1 \\ 0 & 2 \end{pmatrix}
$$

In [46]:
A_4 = [[2, 1, 2], [-2, 3, 0], [2, -1, 3]]
B_4 = [[1, -2], [-4, 1], [0, 2]]

Matriz_A4xB4 = np.matmul(A_4, B_4)
print("Matriz A4 x B4:\n", Matriz_A4xB4)

Matriz A4 x B4:
 [[ -2   1]
 [-14   7]
 [  6   1]]


2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:

$$
a) \begin{pmatrix} 4 & 2 & 6 \\ 3 & 0 & 7 \\ -2 & -1 & -3 \end{pmatrix}
$$


In [47]:
A_5 = [[4, 2, 6], [3, 0, 7], [-2, -1, -3]]

det_A5 = np.linalg.det(A_5)

print("Determinante de la matriz A5:", det_A5)

Determinante de la matriz A5: 0.0


Como el determinante de la matriz es cero, la matriz es singular y no tiene inversa.

$$
b) \begin{pmatrix} 1 & 2 & 0 \\ 2 & 1 & -1 \\ 3 & 1 & 1 \end{pmatrix}
$$

In [48]:
A_6 = [[1, 2, 0], [2, 1, -1], [3, 1, 1]]

det_A6 = np.linalg.det(A_6)

print("Determinante de la matriz A6:", det_A6)

Determinante de la matriz A6: -8.000000000000002


Como el determinante de la matriz es diferente de cero, la matriz es no singular y se puede calcular su inversa:

In [49]:
matriz_inversa_A6 = np.linalg.inv(A_6)
print("Inversa de la matriz A6:\n", matriz_inversa_A6)

Inversa de la matriz A6:
 [[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]


$$
c) \begin{pmatrix} 1 & 1 & -1 & 1 \\ 1 & 2 & -4 & -2 \\ 2 & 1 & 1 & 5 \\ -1 & 0 & -2 & -4 \end{pmatrix}
$$

In [50]:
A_7 = [[1, 1, -1, 1], [1, 2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]]

det_A7 = np.linalg.det(A_7)

print("Determinante de la matriz A7:", det_A7)

Determinante de la matriz A7: 0.0


Como el determinante de la matriz es cero, la matriz es singular y no tiene inversa.

$$
d) \begin{pmatrix} 4 & 0 & 0 & 0 \\ 6 & 7 & 0 & 0 \\ 9 & 11 & 1 & 0 \\ 5 & 4 & 1 & 1 \end{pmatrix}
$$

In [51]:
A_8 = [[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 1, 0], [5, 4, 1, 1]]

det_A8 = np.linalg.det(A_8)

print("Determinante de la matriz A8:", det_A8)

Determinante de la matriz A8: 28.00000000000001


Como el determinante de la matriz es diferente de cero, la matriz es no singular y se puede calcular su inversa:

In [52]:
matriz_inversa_A8 = np.linalg.inv(A_8)
print("Inversa de la matriz A8:\n", matriz_inversa_A8)

Inversa de la matriz A8:
 [[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]


3. Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:

$$
\begin{aligned}
    x_1 - x_2 + 2x_3 - x_4 &= 6, \\
    x_1 \phantom{- x_2} - x_3 + x_4 &= 4, \\
    2x_1 + x_2 + 3x_3 - 4x_4 &= -2, \\
    - x_2 + x_3 - x_4 &= 5;
\end{aligned}
\qquad \qquad
\begin{aligned}
    x_1 - x_2 + 2x_3 - x_4 &= 1, \\
    x_1 \phantom{- x_2} - x_3 + x_4 &= 1, \\
    2x_1 + x_2 + 3x_3 - 4x_4 &= 2, \\
    - x_2 + x_3 - x_4 &= -1.
\end{aligned}
$$

In [53]:
A_coef = [[1, -1, 2, -1], [1, 0, -1, 1], [2, 1, 3, -4], [0, -1, 1, -1]]
b1_ind = [6,4,-2,5]

In [54]:
inversa_Acof = np.linalg.inv(A_coef)
solucion = np.dot(inversa_Acof, b1_ind)
print("Solución del sistema de ecuaciones Ax = b1:\n", solucion)

Solución del sistema de ecuaciones Ax = b1:
 [ 3. -6. -2. -1.]


In [55]:
b2_ind = [1,1,2,-1]
solucion = np.dot(inversa_Acof, b2_ind)
print("Solución del sistema de ecuaciones Ax = b2:\n", solucion)

Solución del sistema de ecuaciones Ax = b2:
 [1. 1. 1. 1.]


4. Encuentre los valores de A que hacen que la siguiente matriz sea singular
$$
A = \begin{pmatrix} 1 & -1 & \alpha \\ 2 & 2 & 1 \\ 0 & \alpha & -\frac{3}{2} \end{pmatrix}

In [56]:
import sympy as sp

alpha = sp.symbols('alpha')

A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

det_A = A.det()
print(f"Determinante de A: {det_A}")

Determinante de A: 2*alpha**2 - alpha - 6.0


El determinante de la matriz A es:
$$
\text{det}(A) = 2\alpha^2 - \alpha - 6
$$

Para que la matriz A sea singular, el determinante debe ser igual a cero, entonces resolvemos la ecuación cuadrática y se obtienen los valores de α:

In [57]:
soluciones = sp.solve(det_A, alpha)
print(f"Valores de alfa para que A sea singular: {soluciones}")

Valores de alfa para que A sea singular: [-1.50000000000000, 2.00000000000000]


5. Resuelva los siguientes sistemas lineales:
$$
a) \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ -1 & 0 & 1\end{pmatrix} \begin{pmatrix} 2 & 3 & -1 \\ 0 & -2 & 1 \\ 0 & 0 & 3\end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ x_3\end{pmatrix} = \begin{pmatrix} 2 \\ -1 \\ 1\end{pmatrix}
$$

In [58]:
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

import numpy as np

def resolver_LU(L: np.ndarray, U: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante la descomposición LU.

    ## Parameters

    ``L``: matriz triangular inferior.

    ``U``: matriz triangular superior.

    ``b``: vector de términos independientes.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """

    n = L.shape[0]

    # --- Sustitución hacia adelante
    logging.info("Sustitución hacia adelante")

    y = np.zeros((n, 1), dtype=float)

    y[0] = b[0] / L[0, 0]

    for i in range(1, n):
        suma = 0
        for j in range(i):
            suma += L[i, j] * y[j]
        y[i] = (b[i] - suma) / L[i, i]

    logging.info(f"y = \n{y}")

    # --- Sustitución hacia atrás
    logging.info("Sustitución hacia atrás")
    sol = np.zeros((n, 1), dtype=float)

    sol[-1] = y[-1] / U[-1, -1]

    for i in range(n - 2, -1, -1):
        logging.info(f"i = {i}")
        suma = 0
        for j in range(i + 1, n):
            suma += U[i, j] * sol[j]
        logging.info(f"suma = {suma}")
        logging.info(f"U[i, i] = {U[i, i]}")
        logging.info(f"y[i] = {y[i]}")
        sol[i] = (y[i] - suma) / U[i, i]

    logging.debug(f"x = \n{sol}")
    return sol

[01-28 09:24:31][INFO] 2026-01-28 09:24:31.251940


In [59]:
L_1 = np.array([[1, 0, 0], [2, 1, 0], [-1, 0, 1]], dtype=float)
U_1 = np.array([[2, 3, -1], [0, -2, 1], [0, 0, 3]], dtype=float)
b_1 = np.array([[2], [-1], [1]], dtype=float)
sol_1 = resolver_LU(L_1, U_1, b_1)
print("Solución del sistema lineal 5a:\n", sol_1)

[01-28 09:24:31][INFO] Sustitución hacia adelante
[01-28 09:24:31][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[01-28 09:24:31][INFO] Sustitución hacia atrás
[01-28 09:24:31][INFO] i = 1
[01-28 09:24:31][INFO] suma = [1.]
[01-28 09:24:31][INFO] U[i, i] = -2.0
[01-28 09:24:31][INFO] y[i] = [-5.]
[01-28 09:24:31][INFO] i = 0
[01-28 09:24:31][INFO] suma = [8.]
[01-28 09:24:31][INFO] U[i, i] = 2.0
[01-28 09:24:31][INFO] y[i] = [2.]
Solución del sistema lineal 5a:
 [[-3.]
 [ 3.]
 [ 1.]]


$$
b) \begin{pmatrix} 2 & 0 & 0 \\ -1 & 1 & 0 \\ 3 & 2 & -1\end{pmatrix} \begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1\end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ x_3\end{pmatrix} = \begin{pmatrix} -1 \\ 3 \\ 0\end{pmatrix}
$$

In [60]:
L_2 = np.array([[2, 0, 0], [-1, 1, 0], [3, 2, -1]], dtype=float)
U_2 = np.array([[1, 1, 1], [0, 1, 2], [0, 0, 1]], dtype=float)
b_2 = np.array([[-1], [3], [0]], dtype=float)
sol_2 = resolver_LU(L_2, U_2, b_2)
print("Solución del sistema lineal 5b:\n", sol_2)

[01-28 09:24:31][INFO] Sustitución hacia adelante
[01-28 09:24:31][INFO] y = 
[[-0.5]
 [ 2.5]
 [ 3.5]]
[01-28 09:24:31][INFO] Sustitución hacia atrás
[01-28 09:24:31][INFO] i = 1
[01-28 09:24:31][INFO] suma = [7.]
[01-28 09:24:31][INFO] U[i, i] = 1.0
[01-28 09:24:31][INFO] y[i] = [2.5]
[01-28 09:24:31][INFO] i = 0
[01-28 09:24:31][INFO] suma = [-1.]
[01-28 09:24:31][INFO] U[i, i] = 1.0
[01-28 09:24:31][INFO] y[i] = [-0.5]
Solución del sistema lineal 5b:
 [[ 0.5]
 [-4.5]
 [ 3.5]]


6. Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU
con lii = 1 para todas las i.

$$
a) \begin{pmatrix} 2 & -1 & 1 \\ 3 & 3 & 9 \\ 3 & 3 & 5 \end{pmatrix}
$$

In [61]:
# ####################################################################
def descomposicion_LU(A: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Realiza la descomposición LU de una matriz cuadrada A.
    [IMPORTANTE] No se realiza pivoteo.

    ## Parameters

    ``A``: matriz cuadrada de tamaño n-by-n.

    ## Return

    ``L``: matriz triangular inferior.

    ``U``: matriz triangular superior. Se obtiene de la matriz ``A`` después de aplicar la eliminación gaussiana.
    """

    A = np.array(
        A, dtype=float
    )  # convertir en float, porque si no, puede convertir como entero

    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]

    L = np.zeros((n, n), dtype=float)

    for i in range(0, n):  # loop por columna

        # --- deterimnar pivote
        if A[i, i] == 0:
            raise ValueError("No existe solución única.")

        # --- Eliminación: loop por fila
        L[i, i] = 1
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            L[j, i] = m

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    return L, A

In [62]:
matriz_a = np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]], dtype=float)

L_1, U_1 = descomposicion_LU(matriz_a)

print("\nMatriz L de la descomposición LU:\n", L_1)
print("\nMatriz U de la descomposición LU:\n", U_1)

[01-28 09:24:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[01-28 09:24:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-28 09:24:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]

Matriz L de la descomposición LU:
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

Matriz U de la descomposición LU:
 [[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


$$
b) \begin{pmatrix} 1.012 & -2.132 & 3.104 \\ -2.132 & 4.096 & -7.013 \\ 3.104 & -7.013 & 0.014 \end{pmatrix}
$$

In [63]:
matriz_b = np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]], dtype=float)

L_2, U_2 = descomposicion_LU(matriz_b)

print("\nMatriz L de la descomposición LU:\n", L_2)
print("\nMatriz U de la descomposición LU:\n", U_2)

[01-28 09:24:31][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-28 09:24:31][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-28 09:24:31][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]

Matriz L de la descomposición LU:
 [[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]

Matriz U de la descomposición LU:
 [[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


$$
c) \begin{pmatrix} 2 & 0 & 0 & 0 \\ 1 & 1.5 & 0 & 0 \\ 0 & -3 & 0.5 & 0 \\ 2 & -2 & 1 & 1 \end{pmatrix}
$$

In [64]:
matriz_c = np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]], dtype=float)

L_3, U_3 = descomposicion_LU(matriz_c)

print("\nMatriz L de la descomposición LU:\n", L_3)
print("\nMatriz U de la descomposición LU:\n", U_3)

[01-28 09:24:31][INFO] 
[[ 2.   0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 0.  -2.   1.   1. ]]
[01-28 09:24:31][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  1.  1. ]]
[01-28 09:24:31][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-28 09:24:31][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]

Matriz L de la descomposición LU:
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]

Matriz U de la descomposición LU:
 [[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


$$
d) \begin{pmatrix} 2.1756 & 4.0231 & -2.1732 & 5.1967 \\ -4.0231 & 6.0000 & 0 & 1.1973 \\ -1.0000 & -5.2107 & 1.1111 & 0 \\ 6.0235 & 7.0000 & 0 & -4.1561 \end{pmatrix}
$$

In [65]:
matriz_d = np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]], dtype=float)

L_4, U_4 = descomposicion_LU(matriz_d)

print("\nMatriz L de la descomposición LU:\n", L_4)
print("\nMatriz U de la descomposición LU:\n", U_4)

[01-28 09:24:31][INFO] 
[[  2.1756       4.0231      -2.1732       5.1967    ]
 [  0.          13.43948042  -4.01866194  10.80699101]
 [  0.          -3.36150897   0.11220314   2.38862842]
 [  0.          -4.13860216   6.01685521 -18.54400331]]
[01-28 09:24:31][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  4.77933394e+00 -1.52160595e+01]]
[01-28 09:24:31][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.20361280e+01]]
[01-28 09:24:31][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.000000

7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.

Literal a.

$$
\begin{aligned}
    2x_1 - x_2 + x_3 &= -1, \\
    3x_1 + 3x_2 + 9x_3 &= 0, \\
    3x_1 + 3x_2 + 5x_3 &= 4. \\
\end{aligned}
$$

In [66]:
# ####################################################################
def eliminacion_gauss_descomposicionLU(A: np.ndarray, b: np.ndarray) -> tuple[np.ndarray, np.ndarray]:

    A = np.array(
        A, dtype=float
    )  # convertir en float, porque si no, puede convertir como entero

    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]

    L = np.zeros((n, n), dtype=float)

    for i in range(0, n):  

        if A[i, i] == 0:
            raise ValueError("No existe solución única.")

        L[i, i] = 1
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            L[j, i] = m

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    logging.info(f"\nMatriz L de la descomposición LU:\n{L}")
    logging.info(f"\nMatriz U de la descomposición LU:\n{A}")

    U = A

    n = L.shape[0]

    logging.info("Sustitución hacia adelante")

    y = np.zeros((n, 1), dtype=float)

    y[0] = b[0] / L[0, 0]

    for i in range(1, n):
        suma = 0
        for j in range(i):
            suma += L[i, j] * y[j]
        y[i] = (b[i] - suma) / L[i, i]

    logging.info(f"y = \n{y}")

    logging.info("Sustitución hacia atrás")
    sol = np.zeros((n, 1), dtype=float)

    sol[-1] = y[-1] / U[-1, -1]

    for i in range(n - 2, -1, -1):
        logging.info(f"i = {i}")
        suma = 0
        for j in range(i + 1, n):
            suma += U[i, j] * sol[j]
        logging.info(f"suma = {suma}")
        logging.info(f"U[i, i] = {U[i, i]}")
        logging.info(f"y[i] = {y[i]}")
        sol[i] = (y[i] - suma) / U[i, i]

    logging.debug(f"x = \n{sol}")

    return sol

In [67]:
A_7a = np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]], dtype=float)
b_7a = np.array([[-1], [0], [4]], dtype=float)
sol_7a = eliminacion_gauss_descomposicionLU(A_7a, b_7a)
print("Solución del sistema lineal 7a:\n", sol_7a)

[01-28 09:24:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[01-28 09:24:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-28 09:24:31][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-28 09:24:31][INFO] 
Matriz L de la descomposición LU:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
[01-28 09:24:31][INFO] 
Matriz U de la descomposición LU:
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-28 09:24:31][INFO] Sustitución hacia adelante
[01-28 09:24:31][INFO] y = 
[[-1. ]
 [ 1.5]
 [ 4. ]]
[01-28 09:24:31][INFO] Sustitución hacia atrás
[01-28 09:24:31][INFO] i = 1
[01-28 09:24:31][INFO] suma = [-7.5]
[01-28 09:24:31][INFO] U[i, i] = 4.5
[01-28 09:24:31][INFO] y[i] = [1.5]
[01-28 09:24:31][INFO] i = 0
[01-28 09:24:31][INFO] suma = [-3.]
[01-28 09:24:31][INFO] U[i, i] = 2.0
[01-28 09:24:31][INFO] y[i] = [-1.]
Solución del sistema lineal 7a:
 [[ 1.]
 [ 2.]
 [-1.]]


$$
\begin{aligned}
    1.012x_1 - 2.132x_2 + 3.104x_3 &= 1.984, \\
    -2.132x_1 +4.096x_2 - 7.013x_3 &= -5.049, \\
    3.104x_1 - 7.013x_2 + 0.014x_3 &= -3.895.
\end{aligned}

In [68]:
A_7b = np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]], dtype=float)
b_7b = np.array([[1.984], [-5.049], [-3.895]], dtype=float)
sol_7b = eliminacion_gauss_descomposicionLU(A_7b, b_7b)
print("Solución del sistema lineal 7b:\n", sol_7b)

[01-28 09:24:31][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-28 09:24:31][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-28 09:24:31][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-28 09:24:31][INFO] 
Matriz L de la descomposición LU:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
[01-28 09:24:31][INFO] 
Matriz U de la descomposición LU:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-28 09:24:31][INFO] Sustitución hacia adelante
[01-28 09:24:31][INFO] y = 
[[ 1.984     ]
 [-0.86926877]
 [-8.93914077]]
[01-28 09:24:31][INFO] Sustitución hacia atrás
[01-28 09:24:31][INFO] i = 1
[01-28 09:24:31][INFO]

$$
\begin{aligned}
    2x_1 \phantom{- x_2} \phantom{- x_2} \phantom{- x_2} \phantom{- x_2} &= 3, \\
    x_1 + 1.5x_2 \phantom{- x_2} \phantom{- x_2} &= 4.5, \\
    \phantom{- x_2} - 3x_2 + 0.5x_3 \phantom{- x_2} &= -6.6, \\
    2x_1 - 2x_2 + x_3 + x_4&= 0.8.
\end{aligned}

In [69]:
A_7c = np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]], dtype=float)
b_7c = np.array([[3], [4.5], [-6.6], [0.8]], dtype=float)
sol_7c = eliminacion_gauss_descomposicionLU(A_7c, b_7c)
print("Solución del sistema lineal 7c:\n", sol_7c)

[01-28 09:24:31][INFO] 
[[ 2.   0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 0.  -2.   1.   1. ]]
[01-28 09:24:31][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  1.  1. ]]
[01-28 09:24:31][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-28 09:24:31][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-28 09:24:31][INFO] 
Matriz L de la descomposición LU:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]
[01-28 09:24:31][INFO] 
Matriz U de la descomposición LU:
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[01-28 09:24:31][INFO] Sustitución hacia adelante
[01-28 09:24:31][INFO] y = 
[[ 3. ]
 [ 3. ]
 [-0.6]
 [ 3. ]]
[01-28 09:24:31][INFO] Sustitución hacia atrás
[01-28 09:24:31][INFO] i

$$
\begin{aligned}
    2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 &= 17.102, \\
    -4.0231x_1 + 6.0000x_2 \phantom{- x_2} + 1.1973x_4 &= -6.1593, \\
    -1.0000x_1 - 5.2107x_2 + 1.1111x_3 \phantom{- x_2}  &= 3.0004, \\
    6.0235x_1 + 7.0000x_2 \phantom{- x_2} - 4.1561x_4 &= 0.0000. \\
\end{aligned}

In [70]:
A_7d = np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]], dtype=float)
b_7d = np.array([[17.102], [-6.1593], [3.0004], [0]], dtype=float)
sol_7d = eliminacion_gauss_descomposicionLU(A_7d, b_7d)
print("Solución del sistema lineal 7d:\n", sol_7d)

[01-28 09:24:31][INFO] 
[[  2.1756       4.0231      -2.1732       5.1967    ]
 [  0.          13.43948042  -4.01866194  10.80699101]
 [  0.          -3.36150897   0.11220314   2.38862842]
 [  0.          -4.13860216   6.01685521 -18.54400331]]
[01-28 09:24:31][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  4.77933394e+00 -1.52160595e+01]]
[01-28 09:24:31][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.20361280e+01]]
[01-28 09:24:31][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.000000